#[cfg(debug_assertions)]
use std::fs;
use std::fs::OpenOptions;
use std::io::Write;
#[cfg(debug_assertions)]
use std::process::Command;

#[cfg(debug_assertions)]
use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri::{
    menu::{Menu, MenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    Emitter, Manager, WindowEvent,
};

mod commands;
mod config;
mod control;
mod password;
mod remote_admin;
mod session;
mod shutdown;
mod windows_session;

#[cfg(debug_assertions)]
const BINDINGS_PATH: &str = "../src/lib/bindings.ts";
#[cfg(debug_assertions)]
const BINDINGS_TEMP_PATH: &str = "../src/lib/.bindings.generated.ts";
#[cfg(debug_assertions)]
const BINDINGS_ROOT_PATH: &str = "src/lib/bindings.ts";
#[cfg(debug_assertions)]
const GENERATED_TYPES_START: &str = "/** user-defined types **/";
#[cfg(debug_assertions)]
const GENERATED_TYPES_END: &str = "/** tauri-specta globals **/";

pub(crate) fn log_error(msg: &str) {
    if let Ok(mut file) = OpenOptions::new()
        .create(true)
        .append(true)
        .open("sessionizer_error.log")
    {
        let _ = writeln!(file, "{}", msg);
    }
    eprintln!("{}", msg);
}

fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::get_config,
        commands::finish_setup,
        commands::update_settings,
        commands::is_first_run,
        commands::setup_password,
        commands::verify_password,
        commands::verify_recovery_key,
        commands::reset_password_with_recovery,
        commands::change_password,
        commands::start_timer,
        commands::clear_timer,
        commands::pause_timer,
        commands::resume_timer,
        commands::get_remaining_seconds,
        commands::mark_warning_notification_sent,
        commands::execute_expired_action,
        commands::get_admin_session_snapshot,
        commands::get_admin_panel_info,
        commands::quit_app,
    ])
}

#[cfg(debug_assertions)]
fn extract_binding_types(source: &str) -> Result<String, String> {
    let start = source
        .find(GENERATED_TYPES_START)
        .ok_or_else(|| "Failed to locate generated types section".to_string())?;
    let end = source
        .find(GENERATED_TYPES_END)
        .ok_or_else(|| "Failed to locate generated globals section".to_string())?;
    let types = source[start + GENERATED_TYPES_START.len()..end].trim();

    let mut output = String::from(
        "// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.\n",
    );

    if !types.is_empty() {
        output.push('\n');
        output.push_str(types);
        output.push('\n');
    }

    Ok(output)
}

#[cfg(debug_assertions)]
fn export_bindings(builder: &tauri_specta::Builder<tauri::Wry>) -> Result<(), String> {
    builder
        .export(
            Typescript::default().bigint(BigIntExportBehavior::Number),
            BINDINGS_TEMP_PATH,
        )
        .map_err(|e| e.to_string())?;
    let generated = fs::read_to_string(BINDINGS_TEMP_PATH).map_err(|e| e.to_string())?;
    let types_only = extract_binding_types(&generated)?;
    let _ = fs::remove_file(BINDINGS_TEMP_PATH);

    fs::write(BINDINGS_PATH, types_only).map_err(|e| e.to_string())?;

    let status = Command::new("pnpm")
        .args([
            "--dir",
            "..",
            "exec",
            "biome",
            "format",
            "--write",
            BINDINGS_ROOT_PATH,
        ])
        .status()
        .map_err(|e| e.to_string())?;

    if status.success() {
        Ok(())
    } else {
        Err("Failed to format generated TypeScript bindings".to_string())
    }
}

pub fn run() {
    let is_autostart_launch = std::env::args().any(|arg| arg == "--minimized");

    std::panic::set_hook(Box::new(|panic_info| {
        log_error(&format!("PANIC: {}", panic_info));
    }));

    log_error("Starting Sessionizer...");

    let specta_builder = build_specta_builder();

    #[cfg(debug_assertions)]
    if let Err(error) = export_bindings(&specta_builder) {
        log_error(&format!("Failed to export TypeScript bindings: {}", error));
    }

    let result = tauri::Builder::default()
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--minimized"]),
        ))
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            log_error("Single instance triggered");
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            log_error("Running setup...");

            let remote_admin_state = remote_admin::RemoteAdminState::default();
            remote_admin::start_server(app.handle().clone(), remote_admin_state.clone());
            app.manage(remote_admin_state);

            if let Err(error) = session::apply_startup_policy(is_autostart_launch) {
                log_error(&format!("Failed to apply startup policy: {}", error));
            }

            let settings_item = MenuItem::with_id(app, "settings", "Settings", true, None::<&str>)?;
            let relock_item = MenuItem::with_id(app, "relock", "Re-lock", true, None::<&str>)?;
            let resume_item =
                MenuItem::with_id(app, "resume-session", "Resume Session", true, None::<&str>)?;
            let about_item = MenuItem::with_id(app, "about", "About", true, None::<&str>)?;
            let quit_item = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;

            let menu = Menu::with_items(
                app,
                &[
                    &settings_item,
                    &relock_item,
                    &resume_item,
                    &about_item,
                    &quit_item,
                ],
            )?;

            if let Some(window) = app.get_webview_window("main") {
                if let Err(error) = windows_session::install(&window) {
                    log_error(&format!(
                        "Failed to install Windows session hook: {}",
                        error
                    ));
                }
            }

            match TrayIconBuilder::new()
                .menu(&menu)
                .on_menu_event(|app, event| {
                    let id = event.id.as_ref();
                    match id {
                        "settings" => {
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.emit("show-settings", ());
                                let _ = window.show();
                                let _ = window.set_focus();
                            }
                        }
                        "relock" => {
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.emit("re-lock", ());
                                let _ = window.show();
                                let _ = window.set_focus();
                            }
                        }
                        "resume-session" => {
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.emit("resume-session", ());
                            }
                        }
                        "about" => {
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.emit("show-about", ());
                                let _ = window.show();
                            }
                        }
                        "quit" => {
                            if let Some(window) = app.get_webview_window("main") {
                                let _ = window.emit("quit-app", ());
                                let _ = window.show();
                            }
                        }
                        _ => {}
                    }
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                })
                .build(app)
            {
                Ok(_tray) => log_error("Tray icon created successfully"),
                Err(error) => log_error(&format!("Failed to create tray icon: {}", error)),
            }

            log_error("Setup complete");
            Ok(())
        })
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                if window.label() == "main" {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .run(tauri::generate_context!());

    match result {
        Ok(_) => log_error("App exited normally"),
        Err(error) => log_error(&format!("App error: {}", error)),
    }
}

#[cfg(test)]
mod bindings {
    use super::*;

    #[test]
    fn export_bindings_snapshot() {
        #[cfg(debug_assertions)]
        export_bindings(&build_specta_builder()).expect("Failed to export TypeScript bindings");
    }
}
